### ISSUE TITLE
Timezones not included in schedule

### ISSUE THREAD

**Issue by Cubaza** [MVP-Greenhouse/ngPolandConfApp#45]
Hi,

I think there is a problem with time on conference schedule. First talk starts at 10:00AM in app (both Android and iOS) first talk starts at 9:00AM. I think app don't parse time to current timezone but it stays in UTC. 
  
There is also problem with load whole schedule. It ends on 12:00PM. For example last year event is loaded full.

**Comment by sebastiandenis** [comment]
Thanks! We're working on this one.

**Comment by CarlosReyesM** [comment]
this bug also affect to the countdown.
Timezone is not in consideration.

**Comment by Cubaza** [comment]
I don't know if CarlosReyesM issue was resolved because countdown stops, but my issue od resolved. Thank You.
